# RevisCore by fxreason
# Build: 0.2.1

# Сообщения
messages:
  no-homes-points: "§b✽ §7➛ §fУ вас нет точек дома! Создать новую точку дома: /sethome"
  one-point-home: "§b✽ §7➛ §fУ вас доступна только одна точка дома с названием: §a"
  home-error: "§b✽ §7➛ §fОшибка чтения данных, обратитесь к администратору!"
  more-points-home: "§b✽ §7➛ §fУ вас несколько точек дома, выберите одну из них."
  teleported-player-home: "§b✽ §7➛ §fВы были успешно телепортированы к точке дома."
  not-found-point-home: "§b✽ §7➛ §fТочка дома с именем §a"
  usage-home: "§b✽ §7➛ §fИспользование: /home [название точки дома]"
  world-not-found: "§b✽ §7➛ §fМир, в котором находится ваша точка дома не найден!"
  error-loads-coords: "§b✽ §7➛ §fУпс! При попытке загрузить координаты вашей точки дома возникла ошибка, попробуйте еще раз."
  enter-home-point: "§b✽ §7➛ §fУкажите название точки дома! (/sethome [название точки])"
  duplicate-name-home: "§b✽ §7➛ §fТочка дома с таким названием уже существует! Придумай что-то новое ;)"
  max-points-sethome: "§b✽ §7➛ §fВы уже установили максимальное количество точек дома!"
  succes-enter-sethome: "§b✽ §7➛ §fТочка дома успешно установлена!"
  succes-enter-setspawn: "§b✽ §7➛ §fТочка спавна успешно установлена!"
  no-permission: "§b✽ §7➛ §fУ вас недостаточно прав для выполнения этой команды!"
  duplicate-warp: "§b✽ §7➛ §fВарп с таким названием уже существует!"
  setwarp-name: "§b✽ §7➛ §fУкажите название точки варпа! (/setpwarp [название точки])"
  setwarp-succes: "§b✽ §7➛ §fТочка варпа успешно установлена!"
  spawn-correct: "§b✽ §7➛ §fИспользуйте команду /spawn для телепортации на спавн"
  warp-usage: "§b✽ §7➛ §fИспользование: /warp [название точки варпа]"
  world-not-found-warp: "§b✽ §7➛ §fМир, в котором находится точка варпа не найден!"
  error-loads-coords-warp: "§b✽ §7➛ §fУпс! При попытке загрузить координаты точки варпа возникла ошибка, попробуйте еще раз!"
  success-teleport-to-spawn: "§b✽ §7➛ §fВы успешно телепортированы на спавн!"
  success-teleport-to-warp: "§b✽ §7➛ §fВы успешно телепортированы на варп §a"
  enter-home-point-for-del: "§b✽ §7➛ §fВведите название точки дома для удаления! (/delhome [название точки])"
  home-point-not-found: "§b✽ §7➛ §fУпс! Точка дома с таким названием не найдена! Убедитесь, что вы правильно написали название."
  success-delete-home-point: "§b✽ §7➛ §fТочка дома успешно удалена!"
  fly-enable: "§b✽ §7➛ §fРежим полета успешно установлен!"
  fly-disable: "§b✽ §7➛ §fРежим полета успешно отключен!"
  gamemode-correct-use: "§b✽ §7➛ §fНеправильное использование команды! Используйте /gm [0/1/2/3] для смены режима."
  gamemode-installed: "§b✽ §7➛ §fУстановлен режим игры: §a"
  incorrect-gamemode: "§b✽ §7➛ §fУпс! Данного режима игры не существует!"
  not-found-player: "§b✽ §7➛ §fИгрок с таким никнеймом не найден!"
  usage-invsee: "§b✽ §7➛ §fИспользование: /invsee [никнейм]"
  usage-tpa: "§b✽ §7➛ §fИспользование: /tpa [никнейм]"
  cooldown-command: "§b✽ §7➛ §fВы не можете использовать эту команду еще §a"
  nontp-to-me: "§b✽ §7➛ §fВы не можете отправить запрос самому себе!"
  tpa-response: "§b✽ §7➛ §fЗапрос на телепортацию отправлен к игроку: §a%player%"
  not-message: "§b✽ §7➛ §fНе удалось обработать сообщение, обратитесь к администратору!"
  tpa-response-to-target: "§b✽ §7➛ §fИгрок §a%player% §fхочет телепортироваться к вам!"
  accept-deny-tpa: "§a/tpaccept§f - принять запрос, §c/tpdeny§f - отклонить запрос"
  times-up-tp: "§b✽ §7➛ §fВремя запроса на телепортацию от игрока §a%player% §fистекло."
  times-up-tplayer: "§b✽ §7➛ §fВремя вашего запроса на телепортацию к игроку §a%player% §fистекло"
  not-active-reqtp: "§b✽ §7➛ §fУ вас нет активных запросов на телепортацию!"
  sender-tp-leave: "§b✽ §7➛ §fИгрок, отправивший запрос покинул игру!"
  succes-teleportation: "§b✽ §7➛ §fТелепортация к игроку §a%player% §fуспешно выполнена!"
  succes-tp-for-you: "§b✽ §7➛ §fИгрок §a%player% §fбыл телепортирован к вам!"
  tp-deny: "§b✽ §7➛ §fИгрок §a%player% §cотклонил §fваш запрос на телепортацию!"
  tp-deny-you: "§b✽ §7➛ §fВы отклонили запрос на телепортацию!"
  usage-tp: "§b✽ §7➛ §fИспользование: /tp [никнейм]"
  not-tp-to-you: "§b✽ §7➛ §fВы не можете телепортироваться к себе!"
  feed-usage: "§b✽ §7➛ §fИспользование: /feed [никнейм]"
  feed-success: "§b✽ §7➛ §fГолод игрока успешно восполнен!"
  feed-only-you: "§b✽ §7➛ §fИзвините, но восполнить голод вы можете только себе!"
  suicide: "§b✽ §7➛ §fВы покончили жизнь самоубийством!"
  suicide-usage: "§b✽ §7➛ §fИспользоваие: /suicide"
  success-tphere: "§b✽ §7➛ §fВы успешно телепортировали игрока к себе!"
  tphere-usage: "§b✽ §7➛ §fИспользование: /tphere [никнейм]"
  tphere-not-you-to-you: "§b✽ §7➛ §fВы неможете телепортировать себя к себе"
  tpahere-response: "§b✽ §7➛ §fИгрок §a%player% §fхочет телепортировать вас к себе"
  tpahere-accept: "§b✽ §7➛ §fИгрок принял ваш запрос!"
  tpahere-tp: "§b✽ §7➛ §fВы были телепортированы к игроку §a%player% §f."
  tpahere-usage: "§b✽ §7➛ §fИспользование: /tpahere [никнейм]"
  setday: "§b✽ §7➛ §fУстановлено время суток: §aдень§f."
  day-usage: "§b✽ §7➛ §fИспользование: /day"
  setnight: "§b✽ §7➛ §fУстановлено время суток: §aночь§f."
  night-usage: "§b✽ §7➛ §fИспользование: /night"
  setsun: "§b✽ §7➛ §fУстановлена ясная погода."
  sun-usage: "§b✽ §7➛ §fИспользование: /sun"
  setrain: "§b✽ §7➛ §fУстановлена дождливая погода"
  rain-usage: "§b✽ §7➛ §fИспользование: /rain"
  tppos-succcess: "§b✽ §7➛ §fВы успешно телепортировались на координаты!"
  tppos-usage: "§b✽ §7➛ §fИспользование: /tppos [x] [y] [z]"
  money: "§b✽ §7➛ §fВаш баланс: §a"
  money-player: "§b✽ §7➛ §fБаланс игрока: §a"
  money-usage: "§b✽ §7➛ §fИспользование: /money [никнейм]"
  pay-usage: "§b✽ §7➛ §fИспользование: /pay [никнейм] [сумма]"
  not-pay-you: "§b✽ §7➛ §fВы не можете отправить деньги самому себе."
  pay-not-postive: "§b✽ §7➛ §fКоличество передаваемых монет не может быть отрицательным!"
  pay-not-money: "§b✽ §7➛ §fУ вас недостаточно средств! Посмотреть текущий баланс - /money"
  err-amount: "§b✽ §7➛ §fНеверное количество!"
  pay-not-send: "§b✽ §7➛ §fПеревод не удался! Попробуйте еще раз."
  pay-me-send: "§b✽ §7➛ §fВы отправили §a%amount% §fигроку §a"
  pay-to-send: "§b✽ §7➛ §fВы получили §a%amount% §fот игрока §a"
  givemoney-not-positive: "§b✽ §7➛ §fКоличество выдаваемых монет не может быть отрицательным."
  givemoney-usage: "§b✽ §7➛ §fИспользование: /givemoney [никнейм] [количество]"
  givemoney: "§b✽ §7➛ §fВы выдали §a%amount% §fигроку §a"
  not-near-players: "§b✽ §7➛ §fИгроков неподалеку не обнаружено!"
  near-usage: "§b✽ §7➛ §fИспользование: /near"
  salary-success: "§b✽ §7➛ §fВы получили зарплату в размере §a%amount% §f$!"
  salary-err: "§b✽ §7➛ §fУ вас нет доступной зарплаты!"
  hat-usage: "§b✽ §7➛ §fИспользование: /hat"
  hat-helmet-err: "§b✽ §7➛ §fНа вас уже надет шлем!"
  hat-not-item-mh: "§b✽ §7➛ §fУ вас нет предмета в основной руке!"
  hat-usage-not-blocks: "§b✽ §7➛ §fВы можете надевать только блоки!"
  hat-success: "§b✽ §7➛ §fПредмет успешно надет на голову!"
  ec-usage: "§b✽ §7➛ §fИспользование: /ec"
  wb-usage: "§b✽ §7➛ §fИспользование: /wb"
  tp-start-dntmove: "§b✽ §7➛ §fТелепортация начнется через 7 секунд. Не двигайтесь!"
  tp-start-seven: "§b✽ §7➛ §fТелепортация начнется через 7 секунд. Не получайте урон!"
  tp-canceled-dmg: "§b✽ §7➛ §fТелепортация отменена из-за полученного урона."
  spawn-not-point: "§b✽ §7➛ §fТочка спавна не установлена."
  player-tptoggle: "§b✽ §7➛ §fИгрок отключил запросы на телепортации!"
  tptoggle-usage: "§b✽ §7➛ §fИспользование: /tptoggle"
  tptoggle-on: "§b✽ §7➛ §fЗапросы на телепортацию §aвключены§f!"
  tptoggle-off: "§b✽ §7➛ §fЗапросы на телепортацию §cотключены§f!"
  rtp-notserch: "§b✽ §7➛ §fНе удалось найти безопасное место. Попробуйте еще раз."
  rtp-success: "§b✽ §7➛ §fВы были успешно телепортированы на рандомные координаты!"
  rtp-usage: "§b✽ §7➛ §fИспользование: /rtp [default/long]"
  clear-success: "§b✽ §7➛ §fИвентарь успешно очищен!"
  clear-usage: "§b✽ §7➛ §fИспользование: /clear"
  msg-usage: "§b✽ §7➛ §fИспользование: /msg [никнейм] [сообщение]"
  msg-dontsend-me: "§b✽ §7➛ §fВы не можете отправить сообщение самому себе!"
  msg-toggle-usage: "§b✽ §7➛ §fИспользование: /msgtoggle"
  msg-toggle-target: "§b✽ §7➛ §fИгрок отключил запросы телепортации."
  msg-toggle-player: "§b✽ §7➛ §fУ вас отключены запросы на телепортацию."
  msg-toggle-on: "§b✽ §7➛ §fЛичные сообщения §aвключены"
  msg-toggle-off: "§b✽ §7➛ §fЛичные сообщения §сотключены"
  ad-usage: "§b✽ §7➛ §fИспользование: /ad [рекламное сообщение]"

inventory_names:
  invsee: '§0⚡ Инвентарь: §a'
  salary: '§0⚡ Зарплата'

settings:
  # Телепортация на спавн при первом входе игрока
  teleport-on-first-join: true
  # Начальный баланс игроков
  default-balance: 100.0
  # Мир для rtp
  world: world

# Координаты спавна
spawn:
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
  world: world