# RevisCore by fxreason
# Build: DEV 0.1

# Сообщения
messages:
  no-homes-points: "§b✽ §7➛ §fУ вас нет точек дома! Создать новую точку дома: /sethome"
  one-point-home: "§b✽ §7➛ §fУ вас доступна только одна точка дома с названием: §a"
  home-error: "§b✽ §7➛ §fОшибка чтения данных, обратитесь к администратору!"
  more-points-home: "§b✽ §7➛ §fУ вас несколько точек дома, выберите одну из них."
  teleported-player-home: "§b✽ §7➛ §fВы телепортированы к точке дома §a"
  not-found-point-home: "§b✽ §7➛ §fТочка дома с именем §a"
  usage-home: "§b✽ §7➛ §fИспользование: /home [название точки дома]"
  world-not-found: "§b✽ §7➛ §fМир, в котором находится ваша точка дома не найден!"
  error-loads-coords: "§b✽ §7➛ §fУпс! При попытке загрузить координаты вашей точки дома возникла ошибка, попробуйте еще раз."
  enter-home-point: "§b✽ §7➛ §fУкажите название точки дома! (/sethome [название точки])"
  duplicate-name-home: "§b✽ §7➛ §fТочка дома с таким названием уже существует! Придумай что-то новое ;)"
  max-points-sethome: "§b✽ §7➛ §fВы уже установили максимальное количество точек дома!"
  succes-enter-sethome: "§b✽ §7➛ §fТочка дома успешно установлена!"
  succes-enter-setspawn: "§b✽ §7➛ §fТочка спавна успешно установлена!"
  no-permission: "§b✽ §7➛ §fУ вас недостаточно прав для выполнения этой команды!"
  duplicate-warp: "§b✽ §7➛ §fВарп с таким названием уже существует!"
  setwarp-name: "§b✽ §7➛ §fУкажите название точки варпа! (/setpwarp [название точки])"
  setwarp-succes: "§b✽ §7➛ §fТочка варпа успешно установлена!"
  spawn-correct: "§b✽ §7➛ §fИспользуйте команду /spawn для телепортации на спавн"
  warp-usage: "§b✽ §7➛ §fИспользование: /warp [название точки варпа]"
  world-not-found-warp: "§b✽ §7➛ §fМир, в котором находится точка варпа не найден!"
  error-loads-coords-warp: "§b✽ §7➛ §fУпс! При попытке загрузить координаты точки варпа возникла ошибка, попробуйте еще раз!"
  success-teleport-to-spawn: "§b✽ §7➛ §fВы успешно телепортированы на спавн!"
  success-teleport-to-warp: "§b✽ §7➛ §fВы успешно телепортированы на варп §a"
  enter-home-point-for-del: "§b✽ §7➛ §fВведите название точки дома для удаления! (/delhome [название точки])"
  home-point-not-found: "§b✽ §7➛ §fУпс! Точка дома с таким названием не найдена! Убедитесь, что вы правильно написали название."
  success-delete-home-point: "§b✽ §7➛ §fТочка дома успешно удалена!"
  fly-enable: "§b✽ §7➛ §fРежим полета успешно установлен!"
  fly-disable: "§b✽ §7➛ §fРежим полета успешно отключен!"
  gamemode-correct-use: "§b✽ §7➛ §fНеправильное использование команды! Используйте /gm [0/1/2/3] для смены режима."
  gamemode-installed: "§b✽ §7➛ §fУстановлен режим игры: §a"
  incorrect-gamemode: "§b✽ §7➛ §fУпс! Данного режима игры не существует!"
  not-found-player: "§b✽ §7➛ §fИгрок с таким никнеймом не найден!"
  usage-invsee: "§b✽ §7➛ §fИспользование: /invsee [никнейм]"
  usage-tpa: "§b✽ §7➛ §fИспользование: /tpa [никнейм]"
  cooldown-command: "§b✽ §7➛ §fВы не можете использовать эту команду еще §a"
  nontp-to-me: "§b✽ §7➛ §fВы не можете отправить запрос самому себе!"
  tpa-response: "§b✽ §7➛ §fЗапрос на телепортацию отправлен к игроку: §a%player%"
  not-message: "§b✽ §7➛ §fНе удалось обработать сообщение, обратитесь к администратору!"
  tpa-response-to-target: "§b✽ §7➛ §fИгрок §a%player% §fхочет телепортироваться к вам!"
  accept-deny-tpa: "§a/tpaccept§f - принять запрос, §c/tpdeny§f - отклонить запрос"
  times-up-tp: "§b✽ §7➛ §fВремя запроса на телепортацию от игрока §a%player% §fистекло."
  times-up-tplayer: "§b✽ §7➛ §fВремя вашего запроса на телепортацию к игроку §a%player% §fистекло"
  not-active-reqtp: "§b✽ §7➛ §fУ вас нет активных запросов на телепортацию!"
  sender-tp-leave: "§b✽ §7➛ §fИгрок, отправивший запрос покинул игру!"
  succes-teleportation: "§b✽ §7➛ §fТелепортация к игроку §a%player% §fуспешно выполнена!"
  succes-tp-for-you: "§b✽ §7➛ §fИгрок §a%player% §fбыл телепортирован к вам!"
  tp-deny: "§b✽ §7➛ §fИгрок §a%player% §fотменил ваш запрос на телепортацию!"
  tp-deny-you: "§b✽ §7➛ §fВы отклонили запрос на телепортацию!"
  usage-tp: "§b✽ §7➛ §fИспользование: /tp [никнейм]"
  not-tp-to-you: "§b✽ §7➛ §fВы не можете телепортироваться к себе!"
  feed-usage: "§b✽ §7➛ §fИспользование: /feed [никнейм]"
  feed-success: "§b✽ §7➛ §fГолод игрока успешно восполнен!"
  feed-only-you: "§b✽ §7➛ §fИзвините, но восполнить голод вы можете только себе!"
  suicide: "§b✽ §7➛ §fВы покончили жизнь самоубийством!"
  suicide-usage: "§b✽ §7➛ §fИспользоваие: /suicide"
  success-tphere: "§b✽ §7➛ §fВы успешно телепортировали игрока к себе!"
  tphere-usage: "§b✽ §7➛ §fИспользование: /tphere [никнейм]"
  tphere-not-you-to-you: "§b✽ §7➛ §fВы неможете телепортировать себя к себе"

inventory_names:
  invsee: '§0⚡ Инвентарь: §a'

settings:
  # Телепортация на спавн при первом входе игрока
  teleport-on-first-join: true

# Координаты спавна
spawn:
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
  world: world