name: RevisCore
version: '0.1'
main: zxc.fxreason.revisCore.RevisCore
api-version: '1.21'

commands:
  reviscore:
    description: Перегазгрузка конфигурации
    usage: /reviscore reload
  sethome:
    description: Установить точку дома
    usage: /sethome [name]
  home:
    description: Телепортирует на точку дома
    usage: /home
  delhome:
    description: Удаляет указанную точку дома
    usage: /delhome
  setspawn:
    description: Устанавливает точку спавна
    usage: /setspawn
  spawn:
    description: Телепортирует на точку спавна
    usage: /spawn
  setwarp:
    description: Установка точки варпа
    usage: /setwap
  warp:
    description: Телепортация на точку варпа
    usage: /warp [name]
  fly:
    description: Включает полет игроку
    usage: /fly
  gm:
    description: Смена режима игры
    usage: /gm [0/1/2/3]


permissions:
  sethome.set:
    description: Установка дома
    default: true
  sethome.unlimited:
    description: Установка точек дома без лимита
    default: op
  reviscore.setwarp:
    description: Установка точки варпа
    default: op
  reviscore.setspawn:
    description: Установка точки спавна
    default: op
  reviscore.reload:
    description: Перезагрузка конфигурации
    default: op
  reviscore.fly:
    description: Возможность использовать fly
    default: op
  reviscore.gamemode:
    description: Смена режима игры
    default: op
