name: RevisCore
version: '0.1'
main: zxc.fxreason.revisCore.RevisCore
api-version: '1.21'

softdepend: [Vault]

commands:
  reviscore:
    description: Перегазгрузка конфигурации
  sethome:
    description: Установить точку дома
  home:
    description: Телепортирует на точку дома
  delhome:
    description: Удаляет указанную точку дома
  setspawn:
    description: Устанавливает точку спавна
  spawn:
    description: Телепортирует на точку спавна
  setwarp:
    description: Установка точки варпа
  warp:
    description: Телепортация на точку варпа
  fly:
    description: Включает полет игроку
  gm:
    description: Смена режима игры
  enderchest:
    description: Открыть эндер сундук
    aliases:
      - ec
  invsee:
    description: Просмотр инвентаря игрока
  tpa:
    description: Телепортация к игроку
  tpaccept:
    description: Принять тп
  tpdeny:
    description: Отказать тп
  tp:
    description: Телепортация к игроку
  feed:
    description: Восполнить голод игроку
  suicide:
    description: Суицид
  tphere:
    description: Телепортировать игрока к себе
  tpahere:
    description: Отправить запрос на телепортацию к себе
  workbench:
    description: Открыть виртуальный верстак
    aliases:
      - wb
  day:
    description: Установить день
  night:
    description: Установить ночь
  sun:
    description: Установить ясную погоду
  rain:
    description: Установить дождливую погоду
  tppos:
    description: Телепортироваться в указанную точку
  money:
    description: Посмотреть баланс
    aliases:
      - balance
      - bal
  baltop:
    description: Топ игроков по балансу
  pay:
    description: Перевод денег
  givemoney:
    description: Выдача монет
  near:
    description: Поиск игроков неподалеку

permissions:
  sethome.set:
    description: Установка дома
    default: true
  sethome.unlimited:
    description: Установка точек дома без лимита
    default: op
  reviscore.setwarp:
    description: Установка точки варпа
    default: op
  reviscore.setspawn:
    description: Установка точки спавна
    default: op
  reviscore.reload:
    description: Перезагрузка конфигурации
    default: op
  reviscore.fly:
    description: Возможность использовать fly
    default: op
  reviscore.gamemode:
    description: Смена режима игры
    default: op
  reviscore.enderchest-open:
    description: Открыть свой эндерчест
    default: op
  reviscore.enderchest-open-other:
    description: Открывает эндерчест указанного игрока
    default: op
  reviscore.invsee:
    description: Просмотр чужих инвентарей
    default: op
  reviscore.noncooldown-tpa:
    description: Без кд тп
    default: op
  reviscore.cooldown-tpa.15:
    description: 15 sec
    default: op
  reviscore.cooldown-tpa.20:
    description: 20 sec
    default: op
  reviscore.cooldown-tpa.30:
    description: 30 sec
    default: op
  reviscore.cooldown-tpa.45:
    description: 45 sec
    default: op
  reviscore.tp:
    description: Телепортация к игроку
    default: op
  reviscore.feed:
    description: Восполняет голод игроку
    default: op
  reviscore.feed-all:
    description: Возможность восполнять голод всем
    default: op
  reviscore.tphere:
    description: Возможность телепортации игроков к себе без запроса
    default: op
  reviscore.workbench:
    description: Возможность открыть виртуальный верстак
    default: op
  reviscore.day:
    description: Установить день
    default: op
  reviscore.night:
    description: Установить ночь
    default: op
  reviscore.sun:
    description: Установить ясную погоду
    default: op
  reviscore.rain:
    description: Установить дождливую погоду
    default: op
  reviscore.tppos:
    description: Телепортироваться в указанную точку
    default: op
  reviscore.money-see-all:
    description: Просмотр баланса у всех игроков
    default: op
  reviscore.givemoney:
    description: Выдать монеты
    default: op
  reviscore.near:
    description: Поиск игроков неподалеку
    default: op